### ISSUE TITLE
Energy minimization error for 4W56 template

### ISSUE THREAD

**Issue by MehtapIsik** [choderalab/t4-lysozyme-l99a-fah#1]
I run the setup_initial_structures.py. It works for first 2 templates but gives an error for 4W56 initial structure. Final solvated potential energy is concerning, so I think something is wrong with minimization step. Any suggestions? @jchodera 

> Processing 4W56 (RUN2)...
> Creating pdbfixer...
>     findMissingResidues...
>     findNonstandardResidues...
>     replaceNonstandardResidues...
>     findMissingAtoms...
>     addMissingAtoms...
>     Removing all heterogens, including water...
>     addingmissinghydrogens...
> Loading forcefield...
> Creating Modeller object...
> Solvating with tip3p...
> Renumbering and counting waters...
> System contains 11585 waters and ions.
> Subtracting offset...
> Shifting model by [ 5.46479988 -1.6415     -0.72850001] nm
> Writing pdbfixer output...
> Creating OpenMM system...
> Adding barostat...
> Creating solvated simulation...
> Writing modeller output...
> Minimizing energy...
> Initial solvated potential energy : 303510023733.009 kcal/mol
> Final solvated potential energy:  : 303533319647.881 kcal/mol
> Taking a few steps...
> Traceback (most recent call last):
>   File "setup_initial_structures.py", line 247, in <module>
>     simulation.step(nsteps)
>   File "/cbio/jclab/home/misik/anaconda/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
>     self._simulate(endStep=self.currentStep+steps)
>   File "/cbio/jclab/home/misik/anaconda/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 194, in _simulate
>     self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
>   File "/cbio/jclab/home/misik/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4731, in step
>     return _openmm.LangevinIntegrator_step(self, steps)
> Exception: Particle coordinate is nan

**Comment by jchodera** [comment]
Looks like the initial energy is absurdly high! Let me try checking this case myself, but in the meantime, can you inspect the PDB files?

**Comment by MehtapIsik** [comment]
Sure. Am I just looking for a obviously wrong geometry or clash?

**Comment by jchodera** [comment]
Yes, or weird bonds that are really long.

**Comment by MehtapIsik** [comment]
C-terminal leucine carboxylic acid group geometry looks wrong after pdbfixer. One of the oxygens of carboxylic acid is too close to C-alpha carbon that Pymol depicts it as bonded.

**Comment by jchodera** [comment]
Can you attach a PDB file or image?

**Comment by MehtapIsik** [comment]
![screen shot 2016-07-22 at 10 42 08 am](https://cloud.githubusercontent.com/assets/8997658/17061500/d340b78c-4ffc-11e6-8610-abffb79521e2.png)

**Comment by MehtapIsik** [comment]
[minimized.pdb.zip](https://github.com/choderalab/t4-lysozyme-l99a-fah/files/378489/minimized.pdb.zip)
